### PR TITLE
Implement audio speedhack.

### PR DESCRIPTION
**Pull request by lanylow**
Added the "Speedhack Audio" feature. I'm leaving the window alignment to you.

### CODE REVIEW

**Comment by TobyAdd** [comment]
Due to the recent update, I'm unable to merge the pull request. Could you update the code for the new version of GDH? Thank you.

**Comment by TobyAdd** [comment]
I can make your changes myself, but GitHub won't include you as a contributor to this repository.

**Comment by lanylow** [comment]
Hello, yes you can make the changes yourself. I've been thinking about this a little bit more, and considering that the audio pitch can now be changed with triggers you might want to hook setPitch in order to maintain the right audio speed, I'd guess that the method I used would desync the audio if such trigger was used. I haven't tested that so I'm just saying this as a thing to look out for.

**Comment by TobyAdd** [comment]
Yeah, RobTop triggers functions to slow down the music, and by hooking the function that alters the music speed, you can multiply the argument number by your own speed for the speedhack to properly slow down the audio

**Comment by westillthinking** [comment]
So is this going to be merged?

**Pull request closed without merging**
