### PR TITLE
2.202 hooks

### PR DESCRIPTION
**Pull request by lilnibblit**

### CODE REVIEW

**Comment by Prevter** [comment]
Just a quick note, it seems that noclip has not only changed the address, but also one byte in both on/off lines
game was crashing for me with the values from previous version.
This has fixed it for me:
> "off": "0F 85 9B 07 00 00 38 83 ~BA~ **C2** 2A 00 00 0F 85 8F 07 00 00",
> "on": "90 90 90 90 90 90 C6 83 ~80~ **88** 2D 00 00 01 E9 8F 07 00 00"

**Comment by lilnibblit** [comment]
oh thanks

**Comment by Magicland115** [comment]
When will 2.201 hacks come out?

**Comment by zamzibar-bofh** [comment]
Hi guys, today the new 2.204 go live! the game crash :C

**Comment by EnderNon** [comment]
> Hi guys, today the new 2.204 go live! the game crash :C My son is your best betatester hehehehe!

what?

**Comment by Magicland115** [comment]
> Hi guys, today the new 2.204 go live! the game crash :C My son is your best betatester hehehehe!

what?

**Comment by gibbey234** [comment]
still refuses to work

**Pull request closed without merging**
